/*
# Additive Migration: School Education & Student Enrollment System (1. LÉPCSŐ)

## Purpose
Adds the database-level infrastructure for the Iskola -> Oktató -> Szakma -> Tanuló workflow:
1. `partner_user_trades`: Links school staff/instructors (partner_users) to specific construction trades (trade_id).
2. `student_invitation_codes`: Reusable class invitation codes generated by instructors for specific trades.
3. `school_students`: Student enrollment memberships binding student_id -> (school_id, instructor_id, trade_id).
4. Hardened SECURITY DEFINER RPCs: `get_student_code_info` and `redeem_student_invitation_code`.
*/

-- ===============================================================================
-- 1. TABLES
-- ===============================================================================

-- 1.1 Instructor Trade Assignments Table
CREATE TABLE IF NOT EXISTS partner_user_trades (
  partner_id   uuid NOT NULL,
  user_id      uuid NOT NULL,
  trade_id     text NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (partner_id, user_id, trade_id),
  CONSTRAINT fk_partner_user_trades_partner_users
    FOREIGN KEY (partner_id, user_id)
    REFERENCES partner_users(partner_id, user_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_partner_user_trades_partner
    FOREIGN KEY (partner_id)
    REFERENCES partners(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_partner_user_trades_profile
    FOREIGN KEY (user_id)
    REFERENCES profiles(id)
    ON DELETE CASCADE
);

-- 1.2 Class Student Invitation Codes Table
CREATE TABLE IF NOT EXISTS student_invitation_codes (
  id            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  code          text UNIQUE NOT NULL,
  school_id     uuid NOT NULL,
  instructor_id uuid NOT NULL,
  trade_id      text NOT NULL,
  created_by    uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  expires_at    timestamptz NOT NULL,
  status        text NOT NULL DEFAULT 'active',
  usage_count   integer NOT NULL DEFAULT 0,
  max_uses      integer NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_student_invitation_codes_status
    CHECK (status IN ('active', 'inactive', 'expired')),
  CONSTRAINT check_student_invitation_codes_usage_count
    CHECK (usage_count >= 0),
  CONSTRAINT check_student_invitation_codes_max_uses
    CHECK (max_uses IS NULL OR max_uses > 0),
  CONSTRAINT fk_student_invitation_codes_trade
    FOREIGN KEY (school_id, instructor_id, trade_id)
    REFERENCES partner_user_trades(partner_id, user_id, trade_id)
    ON DELETE CASCADE,
  CONSTRAINT fk_student_invitation_codes_school
    FOREIGN KEY (school_id)
    REFERENCES partners(id)
    ON DELETE CASCADE,
  CONSTRAINT fk_student_invitation_codes_instructor
    FOREIGN KEY (instructor_id)
    REFERENCES profiles(id)
    ON DELETE CASCADE
);

-- 1.3 School Student Memberships Table
CREATE TABLE IF NOT EXISTS school_students (
  id                 uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  school_id          uuid NOT NULL REFERENCES partners(id) ON DELETE CASCADE,
  instructor_id      uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  trade_id           text NOT NULL,
  student_id         uuid NOT NULL REFERENCES profiles(id) ON DELETE CASCADE,
  invitation_code_id uuid NULL REFERENCES student_invitation_codes(id) ON DELETE SET NULL,
  status             text NOT NULL DEFAULT 'active',
  joined_at          timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT check_school_students_status
    CHECK (status IN ('active', 'graduated', 'inactive')),
  CONSTRAINT unique_student_school_trade
    UNIQUE (student_id, school_id, trade_id)
);

-- ===============================================================================
-- 2. INDEXES
-- ===============================================================================

CREATE INDEX IF NOT EXISTS idx_partner_user_trades_user_id
  ON partner_user_trades(user_id, partner_id);

CREATE INDEX IF NOT EXISTS idx_student_invitation_codes_lookup
  ON student_invitation_codes(school_id, instructor_id, status, expires_at);

CREATE INDEX IF NOT EXISTS idx_school_students_student_id
  ON school_students(student_id);

CREATE INDEX IF NOT EXISTS idx_school_students_lookup
  ON school_students(school_id, instructor_id, trade_id);

-- ===============================================================================
-- 3. ROW LEVEL SECURITY (RLS) POLICIES
-- ===============================================================================

ALTER TABLE partner_user_trades ENABLE ROW LEVEL SECURITY;
ALTER TABLE student_invitation_codes ENABLE ROW LEVEL SECURITY;
ALTER TABLE school_students ENABLE ROW LEVEL SECURITY;

-- 3.1 partner_user_trades Policies
DROP POLICY IF EXISTS "Read partner_user_trades" ON partner_user_trades;
CREATE POLICY "Read partner_user_trades" ON partner_user_trades
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR user_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = partner_user_trades.partner_id
        AND pu.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Manage partner_user_trades" ON partner_user_trades;
CREATE POLICY "Manage partner_user_trades" ON partner_user_trades
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = partner_user_trades.partner_id
        AND pu.user_id = auth.uid()
        AND pu.member_role = 'owner'
    )
  );

-- 3.2 student_invitation_codes Policies
DROP POLICY IF EXISTS "Read student_invitation_codes" ON student_invitation_codes;
CREATE POLICY "Read student_invitation_codes" ON student_invitation_codes
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR instructor_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = student_invitation_codes.school_id
        AND pu.user_id = auth.uid()
        AND pu.member_role = 'owner'
    )
  );

DROP POLICY IF EXISTS "Insert student_invitation_codes" ON student_invitation_codes;
CREATE POLICY "Insert student_invitation_codes" ON student_invitation_codes
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR (
      instructor_id = auth.uid()
      AND EXISTS (
        SELECT 1 FROM partner_user_trades put
        WHERE put.partner_id = student_invitation_codes.school_id
          AND put.user_id = auth.uid()
          AND put.trade_id = student_invitation_codes.trade_id
      )
    )
  );

DROP POLICY IF EXISTS "Update/Delete student_invitation_codes" ON student_invitation_codes;
CREATE POLICY "Update/Delete student_invitation_codes" ON student_invitation_codes
  FOR UPDATE TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR instructor_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = student_invitation_codes.school_id
        AND pu.user_id = auth.uid()
        AND pu.member_role = 'owner'
    )
  );

-- 3.3 school_students Policies
DROP POLICY IF EXISTS "Read school_students" ON school_students;
CREATE POLICY "Read school_students" ON school_students
  FOR SELECT TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role IN ('admin', 'editor'))
    OR student_id = auth.uid()
    OR instructor_id = auth.uid()
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = school_students.school_id
        AND pu.user_id = auth.uid()
    )
  );

DROP POLICY IF EXISTS "Admin insert school_students" ON school_students;
CREATE POLICY "Admin insert school_students" ON school_students
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
  );

DROP POLICY IF EXISTS "Manage school_students" ON school_students;
CREATE POLICY "Manage school_students" ON school_students
  FOR ALL TO authenticated
  USING (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
    OR EXISTS (
      SELECT 1 FROM partner_users pu
      WHERE pu.partner_id = school_students.school_id
        AND pu.user_id = auth.uid()
        AND pu.member_role = 'owner'
    )
  );

-- ===============================================================================
-- 4. HARDENED SECURITY DEFINER RPC FUNCTIONS
-- ===============================================================================

-- RPC 1: Public/Authenticated Code Info Validation
CREATE OR REPLACE FUNCTION get_student_code_info(input_code TEXT)
RETURNS jsonb AS $$
DECLARE
  inv_code RECORD;
BEGIN
  IF input_code IS NULL OR TRIM(input_code) = '' THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Kérjük, adja meg a meghívókódot.');
  END IF;

  SELECT
    sic.code,
    sic.expires_at,
    sic.status,
    sic.usage_count,
    sic.max_uses,
    sic.school_id,
    p.name AS school_name,
    sic.instructor_id,
    pr.full_name AS instructor_name,
    sic.trade_id
  INTO inv_code
  FROM student_invitation_codes sic
  JOIN partners p ON p.id = sic.school_id
  JOIN profiles pr ON pr.id = sic.instructor_id
  WHERE UPPER(TRIM(sic.code)) = UPPER(TRIM(input_code))
    AND sic.status = 'active'
    AND sic.expires_at > now();

  IF NOT FOUND THEN
    RETURN jsonb_build_object('valid', false, 'error', 'Érvénytelen, lejárt vagy nem létező osztálytermi kód.');
  END IF;

  IF inv_code.max_uses IS NOT NULL AND inv_code.usage_count >= inv_code.max_uses THEN
    RETURN jsonb_build_object('valid', false, 'error', 'A megadott meghívókód beváltási kerete betelt.');
  END IF;

  RETURN jsonb_build_object(
    'valid', true,
    'code', inv_code.code,
    'school_id', inv_code.school_id,
    'school_name', inv_code.school_name,
    'instructor_id', inv_code.instructor_id,
    'instructor_name', COALESCE(inv_code.instructor_name, 'Oktató'),
    'trade_id', inv_code.trade_id,
    'expires_at', inv_code.expires_at
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- RPC 2: Server-Side Transactional Student Code Redemption
CREATE OR REPLACE FUNCTION redeem_student_invitation_code(input_code TEXT)
RETURNS jsonb AS $$
DECLARE
  current_user_id UUID;
  current_user_email TEXT;
  inv_code RECORD;
BEGIN
  -- 1. Authentication Check
  current_user_id := auth.uid();
  IF current_user_id IS NULL THEN
    RAISE EXCEPTION 'Hozzáférés megtagadva: Nincs bejelentkezett munkamenet.';
  END IF;

  SELECT email INTO current_user_email FROM profiles WHERE id = current_user_id;
  IF current_user_email IS NULL THEN
    RAISE EXCEPTION 'Felhasználói profil nem található.';
  END IF;

  IF input_code IS NULL OR TRIM(input_code) = '' THEN
    RAISE EXCEPTION 'Kérjük, adja meg a meghívókódot.';
  END IF;

  -- 2. Lock & Fetch code row FOR UPDATE to prevent race conditions
  SELECT
    sic.*,
    p.name AS school_name,
    pr.full_name AS instructor_name
  INTO inv_code
  FROM student_invitation_codes sic
  JOIN partners p ON p.id = sic.school_id
  JOIN profiles pr ON pr.id = sic.instructor_id
  WHERE UPPER(TRIM(sic.code)) = UPPER(TRIM(input_code))
    FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'A megadott osztálytermi kód érvénytelen vagy nem található.';
  END IF;

  -- 3. Expiration and Status Checks
  IF inv_code.status <> 'active' OR inv_code.expires_at <= now() THEN
    RAISE EXCEPTION 'A megadott meghívókód lejárt vagy már nem aktív.';
  END IF;

  IF inv_code.max_uses IS NOT NULL AND inv_code.usage_count >= inv_code.max_uses THEN
    RAISE EXCEPTION 'A megadott meghívókód beváltási kerete betelt.';
  END IF;

  -- 4. Duplicate Check (If already enrolled in this school + trade)
  IF EXISTS (
    SELECT 1 FROM school_students
    WHERE student_id = current_user_id
      AND school_id = inv_code.school_id
      AND trade_id = inv_code.trade_id
  ) THEN
    RETURN jsonb_build_object(
      'success', true,
      'already_enrolled', true,
      'school_id', inv_code.school_id,
      'school_name', inv_code.school_name,
      'trade_id', inv_code.trade_id,
      'message', 'Ön már csatlakozott ehhez a szakmához ebben az iskolában!'
    );
  END IF;

  -- 5. Atomic Counter Increment & Student Membership Insertion
  UPDATE student_invitation_codes
  SET usage_count = usage_count + 1
  WHERE id = inv_code.id;

  INSERT INTO school_students (
    school_id,
    instructor_id,
    trade_id,
    student_id,
    invitation_code_id,
    status,
    joined_at
  ) VALUES (
    inv_code.school_id,
    inv_code.instructor_id,
    inv_code.trade_id,
    current_user_id,
    inv_code.id,
    'active',
    now()
  );

  RETURN jsonb_build_object(
    'success', true,
    'already_enrolled', false,
    'school_id', inv_code.school_id,
    'school_name', inv_code.school_name,
    'instructor_id', inv_code.instructor_id,
    'instructor_name', COALESCE(inv_code.instructor_name, 'Oktató'),
    'trade_id', inv_code.trade_id,
    'message', 'Sikeresen csatlakozott az Iskola szakmai képzéséhez!'
  );
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = public, pg_temp;

-- ===============================================================================
-- 5. EXECUTE GRANTS
-- ===============================================================================

REVOKE EXECUTE ON FUNCTION get_student_code_info(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION get_student_code_info(TEXT) TO authenticated;

REVOKE EXECUTE ON FUNCTION redeem_student_invitation_code(TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION redeem_student_invitation_code(TEXT) TO authenticated;
